#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kimchi
Version  : 2.5.0
Release  : 3
URL      : https://github.com/kimchi-project/kimchi/archive/2.5.0.tar.gz
Source0  : https://github.com/kimchi-project/kimchi/archive/2.5.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.1
Requires: kimchi-data = %{version}-%{release}
Requires: kimchi-license = %{version}-%{release}
Requires: kimchi-locales = %{version}-%{release}
Requires: kimchi-python = %{version}-%{release}
Requires: kimchi-python3 = %{version}-%{release}
Requires: wok
BuildRequires : CherryPy
BuildRequires : libvirt-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt
BuildRequires : libxslt-dev
BuildRequires : pkgconfig(systemd)
BuildRequires : systemd-dev
BuildRequires : wok

%description
* [What is Kimchi?](#what-is-kimchi)
* [Browser Support](https://github.com/kimchi-project/wok/#browser-support)
* [Desktop Browser Support](https://github.com/kimchi-project/wok/#desktop-browser-support)
* [Mobile Browser Support](https://github.com/kimchi-project/wok/#mobile-browser-support)
* [Linux Support](https://github.com/kimchi-project/wok/#linux-support)
* [Getting started](#getting-started)
* [Install Dependencies](#install-dependencies)
* [Build and Install](#build-and-install)
* [Starting up Wok](https://github.com/kimchi-project/wok/#starting-up-wok)
* [Troubleshooting](#troubleshooting)
* [Testing](#testing)
* [Usage](#usage)
* [Contributing to Kimchi Project](#contributing-to-kimchi-project)

%package data
Summary: data components for the kimchi package.
Group: Data

%description data
data components for the kimchi package.


%package license
Summary: license components for the kimchi package.
Group: Default

%description license
license components for the kimchi package.


%package locales
Summary: locales components for the kimchi package.
Group: Default

%description locales
locales components for the kimchi package.


%package python
Summary: python components for the kimchi package.
Group: Default
Requires: kimchi-python3 = %{version}-%{release}

%description python
python components for the kimchi package.


%package python3
Summary: python3 components for the kimchi package.
Group: Default
Requires: python3-core

%description python3
python3 components for the kimchi package.


%prep
%setup -q -n kimchi-2.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540762467
%autogen --disable-static
make

%install
export SOURCE_DATE_EPOCH=1540762467
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kimchi
cp COPYING.ASL2 %{buildroot}/usr/share/package-licenses/kimchi/COPYING.ASL2
cp COPYING.LGPL %{buildroot}/usr/share/package-licenses/kimchi/COPYING.LGPL
%make_install
%find_lang kimchi

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kimchi/doc/API.md
/usr/share/kimchi/doc/README.md
/usr/share/kimchi/doc/fedora-deps.md
/usr/share/kimchi/doc/kimchi-guests.png
/usr/share/kimchi/doc/kimchi-templates.png
/usr/share/kimchi/doc/opensuse-deps.md
/usr/share/kimchi/doc/ubuntu-deps.md
/usr/share/kimchi/doc/wok-login.png
/usr/share/wok/plugins/kimchi/ui/config/tab-ext.xml
/usr/share/wok/plugins/kimchi/ui/css/kimchi.css
/usr/share/wok/plugins/kimchi/ui/images/file-o-img.svg
/usr/share/wok/plugins/kimchi/ui/images/file-o-iso.svg
/usr/share/wok/plugins/kimchi/ui/images/icon-centos.png
/usr/share/wok/plugins/kimchi/ui/images/icon-debian.png
/usr/share/wok/plugins/kimchi/ui/images/icon-fedora.png
/usr/share/wok/plugins/kimchi/ui/images/icon-gentoo.png
/usr/share/wok/plugins/kimchi/ui/images/icon-opensuse.png
/usr/share/wok/plugins/kimchi/ui/images/icon-ubuntu.png
/usr/share/wok/plugins/kimchi/ui/images/icon-vm.png
/usr/share/wok/plugins/kimchi/ui/images/kimchi.svg
/usr/share/wok/plugins/kimchi/ui/js/kimchi.min.js
/usr/share/wok/plugins/kimchi/ui/pages/guest-add.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/guest-clone.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/guest-edit.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/guest-migration.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/guest-storage-add.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/guest.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/help/de_DE/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/de_DE/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/de_DE/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/de_DE/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/en_US/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/en_US/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/en_US/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/en_US/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/es_ES/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/es_ES/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/es_ES/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/es_ES/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/fr_FR/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/fr_FR/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/fr_FR/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/fr_FR/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/it_IT/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/it_IT/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/it_IT/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/it_IT/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ja_JP/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ja_JP/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ja_JP/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ja_JP/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/kimchi.css
/usr/share/wok/plugins/kimchi/ui/pages/help/ko_KR/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ko_KR/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ko_KR/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ko_KR/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/pt_BR/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/pt_BR/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/pt_BR/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/pt_BR/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ru_RU/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ru_RU/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ru_RU/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/ru_RU/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/zh_CN/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/zh_CN/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/zh_CN/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/zh_CN/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/help/zh_TW/guests.html
/usr/share/wok/plugins/kimchi/ui/pages/help/zh_TW/network.html
/usr/share/wok/plugins/kimchi/ui/pages/help/zh_TW/storage.html
/usr/share/wok/plugins/kimchi/ui/pages/help/zh_TW/templates.html
/usr/share/wok/plugins/kimchi/ui/pages/i18n.json.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/network-add.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/network-edit.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/storagepool-add-volume.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/storagepool-add.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/storagepool-resize-volume.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/tabs/guests.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/tabs/network.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/tabs/storage.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/tabs/templates.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/template-add.html.tmpl
/usr/share/wok/plugins/kimchi/ui/pages/template-edit.html.tmpl
/usr/share/wok/plugins/kimchi/ui/serial/html/serial.html
/usr/share/wok/plugins/kimchi/ui/serial/libs/term.js
/usr/share/wok/plugins/kimchi/ui/spice-html5/pages/spice_auto.html

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kimchi/COPYING.ASL2
/usr/share/package-licenses/kimchi/COPYING.LGPL

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f kimchi.lang
%defattr(-,root,root,-)

